name: core-build
on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/araxiaonline/ac-wotlk-worldserver:latest
      options: --user root
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cmake and dependencies
        run: |
          apt-get update
          apt-get install -y cmake make g++ clang

      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY | sed 's|.*/||')" >> $GITHUB_ENV

      - name: Copy module to container
        run: |
          mkdir -p /azerothcore/modules/${{ env.REPO_NAME }}
          cp -r . /azerothcore/modules/${{ env.REPO_NAME }}

      - name: Rebuild Modules
        run: |
          cd /azerothcore/build \
          && cmake ../modules -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          && cmake --build . --config RelWithDebInfo -j $(($(nproc) + 1))

      - name: cpp check
        run: |
          cppcheck --force --inline-suppr --output-file=report.txt /azerothcore/modules/${{ env.REPO_NAME }}
          if [ -s report.txt ]; then
            cat report.txt
            exit 1
          fi
