name: core-build
on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/araxiaonline/ac-wotlk-worldserver-devcontainer:latest
      options: --user root
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repository name
        id: repo-name
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY | sed 's|.*/||')" >> $GITHUB_ENV

      - name: Copy module to container
        run: |
          mkdir -p /azerothcore/modules/${{ env.REPO_NAME }}
          cp -r . /azerothcore/modules/${{ env.REPO_NAME }}

      - name: Rebuild Modules with Caching
        run: |
            cd /azerothcore/
            ./acore.sh docker build

      - name: cpp check
        run: |
          cppcheck --force --inline-suppr --output-file=report.txt /azerothcore/modules/${{ env.REPO_NAME }}
          if [ -s report.txt ]; then
            cat report.txt
            exit 1
          fi
